apiVersion: v1
kind: pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: ngnix-container
      image: ngnix



# kubectl create -f pod-defination.yml
# kubectl get pod
# kubectl describe pod nginx
# kubectl get pod -o wide
# kubectl apply -f replicaset.yml
# kubectl get rs
# kubectl describe name
